name: 唤潮鲛姬娜美 Nami Introduction
url: https://songruhan.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: faculty
    name: 本人SHE
  - key: grad
    name: 基础 basic
  - key: ugrad
    name: 数值 value
  - key: collab
    name: 背景故事 backstory


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 技能 Skill
    link: /research.html
  - title: 皮肤 skin
    link: /publications.html
